### ISSUE TITLE
Running mandb after installation

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/promptersport#1]
After installing, is there a specific directory to run mandb from?
Where does the manual page index get created?
thanks

Installation Caveats
prompters:
Please make sure to run mandb to create or update the manual page index

**Comment by gngrossi** [comment]
Expected result?

bash-5.2$ (unset MANPATH && cd /hewitt/zopentools/zopen_repo-current/usr/local/zopen && mandb .)
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/....
Updating index cache for path `/hewitt/zopentools/zopen_repo/usr/local/zopen/./man-db'. Wait...mandb: warning: /hewitt/zopentools/zopen_repo/usr/local/zopen/./man-db/man-db-2.12.0.20240124_132957.zos: ignoring bogus filename
mandb: warning: /hewitt/zopentools/zopen_repo/usr/local/zopen/./man-db/man-db: ignoring bogus filename
done.
Checking for stray cats under /hewitt/zopentools/zopen_repo/usr/local/zopen/....
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./curl...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./jq...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./meta...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./ncdu...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./zosnc...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./xz...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./powerlinego...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./ninja...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./moreutils...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./make...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./dos2unix...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./rsync...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./bash...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./zospstree...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./tree...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./zoslib...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./zlib...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./zip...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./which...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./wget...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./unzip...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./vim...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./ncurses...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./bzip2...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./c3270...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./coreutils...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./gawk...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./gettext...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./grep...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./groff...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./gzip...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./git...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./less...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./perl...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./tar...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./tig...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./libiconv...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./openssl...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./sed...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./diffutils...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./expat...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./findutils...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./screen...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./sqlite...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./gpg...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./pinentry...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./nano...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./lynx...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./zos-code-page-tools...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./util-linux...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./my_basic...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./groovy...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./gum...
Processing manual pages under /hewitt/zopentools/zopen_repo/usr/local/zopen/./prompters...
1 man subdirectory contained newer manual pages.
0 manual pages were added.
0 stray cats were added.
0 old database entries were purged.

**Comment by IgorTodorovskiIBM** [comment]
Yep, that looks correct. You can also re-create the index from scratch with `mandb -c`. I'm not exactly sure where the cache is stored - would need to take a look. @MikeFultonDev do you know?

**Comment by gngrossi** [comment]
After running the mandb command, index.db was created in /hewitt/zopentools/zopen_repo/usr/local/zopen
thanks

**Comment by gngrossi** [comment]
closing...
